import http from 'node:http';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const root=path.dirname(fileURLToPath(import.meta.url));
try{for(const line of (await readFile(path.join(root,'.env'),'utf8')).split(/\r?\n/)){const m=line.match(/^([A-Z_]+)=(.*)$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2];}}catch(e){if(e.code!=='ENOENT')throw e;}
const send=(res,status,data,type='application/json; charset=utf-8')=>{res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(data);};
export function createServer({key=process.env.ASSEMBLYAI_API_KEY,fetcher=fetch}={}){return http.createServer(async(req,res)=>{try{const p=new URL(req.url,'http://localhost').pathname;if(req.method!=='GET')return send(res,405,JSON.stringify({error:'Method not allowed'}));if(p==='/api/status')return send(res,200,JSON.stringify({configured:!!key}));if(p==='/api/voice-token'){if(!key)return send(res,503,JSON.stringify({error:'Add ASSEMBLYAI_API_KEY to .env to enable voice.'}));const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);let response;try{response=await fetcher('https://agents.assemblyai.com/v1/token?expires_in_seconds=60&max_session_duration_seconds=1200',{headers:{Authorization:`Bearer ${key}`},signal:controller.signal});}finally{clearTimeout(timer);}if(!response.ok)return send(res,502,JSON.stringify({error:`Voice provider rejected token request (${response.status}).`}));const {token}=await response.json();return token?send(res,200,JSON.stringify({token})):send(res,502,JSON.stringify({error:'Voice provider returned no token.'}));}const name=p==='/'?'index.html':p.slice(1);if(!['index.html','app.js','style.css','pcm-processor.js','brief.js','prompt.js','docs-generator.js','zip-store.js'].includes(name))return send(res,404,JSON.stringify({error:'Not found'}));const file=['brief.js','prompt.js','docs-generator.js','zip-store.js'].includes(name)?path.join(root,name):path.join(root,'public',name);return send(res,200,await readFile(file),name.endsWith('.html')?'text/html; charset=utf-8':name.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8');}catch(error){console.error(error);return send(res,500,JSON.stringify({error:'Request failed.'}));}});}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url))createServer().listen(Number(process.env.PORT||3000),()=>console.log(`Briefly at http://localhost:${process.env.PORT||3000}`));
